name: class_mate
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  webview_flutter: ^4.2.2 # for webview
  google_fonts: ^6.1.0  # ✅ Added for custom font styling
  shared_preferences: ^2.2.2
  intl: ^0.18.1
  fl_chart: ^0.64.0
  percent_indicator: ^4.2.2
  flutter_html: ^3.0.0-beta.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # Optional: if you want to add offline font support, add this section and download fonts
  # fonts:
  #   - family: Poppins
  #     fonts:
  #       - asset: assets/fonts/Poppins-SemiBold.ttf
  #   - family: Lato
  #     fonts:
  #       - asset: assets/fonts/Lato-Regular.ttf

  # Optional: if you have image assets, declare them here
  # assets:
  #   - assets/images/
